using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Taus.DataSourceHandlers;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData()
    {
        return new List<DataSourceItem>()
        {
            new DataSourceItem("af", "Afrikaans" ),
            new DataSourceItem("sq", "Albanian" ),
            new DataSourceItem("am", "Amharic" ),
            new DataSourceItem("ar", "Arabic" ),
            new DataSourceItem("hy", "Armenian" ),
            new DataSourceItem("as", "Assamese" ),
            new DataSourceItem("az", "Azerbaijani" ),
            new DataSourceItem("bn", "Bangla" ),
            new DataSourceItem("eu", "Basque" ),
            new DataSourceItem("be", "Belarusian" ),
            new DataSourceItem("bs", "Bosnian" ),
            new DataSourceItem("bg", "Bulgarian" ),
            new DataSourceItem("my", "Burmese" ),
            new DataSourceItem("ca", "Catalan" ),
            new DataSourceItem("ceb", "Cebuano" ),
            new DataSourceItem("zh", "Chinese" ),
            new DataSourceItem("co", "Corsican" ),
            new DataSourceItem("hr", "Croatian" ),
            new DataSourceItem("cs", "Czech" ),
            new DataSourceItem("da", "Danish" ),
            new DataSourceItem("nl", "Dutch" ),
            new DataSourceItem("en", "English" ),
            new DataSourceItem("eo", "Esperanto" ),
            new DataSourceItem("et", "Estonian" ),
            new DataSourceItem("fi", "Finnish" ),
            new DataSourceItem("fr", "French" ),
            new DataSourceItem("gl", "Galician" ),
            new DataSourceItem("ka", "Georgian" ),
            new DataSourceItem("de", "German" ),
            new DataSourceItem("el", "Greek" ),
            new DataSourceItem("gu", "Gujarati" ),
            new DataSourceItem("ht", "Haitian Creole" ),
            new DataSourceItem("ha", "Hausa" ),
            new DataSourceItem("haw", "Hawaiian" ),
            new DataSourceItem("he", "Hebrew" ),
            new DataSourceItem("hi", "Hindi" ),
            new DataSourceItem("hmn", "Hmong" ),
            new DataSourceItem("hu", "Hungarian" ),
            new DataSourceItem("is", "Icelandic" ),
            new DataSourceItem("ig", "Igbo" ),
            new DataSourceItem("id", "Indonesian" ),
            new DataSourceItem("ga", "Irish" ),
            new DataSourceItem("it", "Italian" ),
            new DataSourceItem("ja", "Japanese" ),
            new DataSourceItem("jv", "Javanese" ),
            new DataSourceItem("kn", "Kannada" ),
            new DataSourceItem("kk", "Kazakh" ),
            new DataSourceItem("km", "Khmer" ),
            new DataSourceItem("rw", "Kinyarwanda" ),
            new DataSourceItem("ko", "Korean" ),
            new DataSourceItem("ku", "Kurdish" ),
            new DataSourceItem("ky", "Kyrgyz" ),
            new DataSourceItem("lo", "Lao" ),
            new DataSourceItem("la", "Latin" ),
            new DataSourceItem("lv", "Latvian" ),
            new DataSourceItem("lt", "Lithuanian" ),
            new DataSourceItem("lb", "Luxembourgish" ),
            new DataSourceItem("mk", "Macedonian" ),
            new DataSourceItem("mg", "Malagasy" ),
            new DataSourceItem("ms", "Malay" ),
            new DataSourceItem("ml", "Malayalam" ),
            new DataSourceItem("mt", "Maltese" ),
            new DataSourceItem("mr", "Marathi" ),
            new DataSourceItem("mn", "Mongolian" ),
            new DataSourceItem("mi", "Māori" ),
            new DataSourceItem("ne", "Nepali" ),
            new DataSourceItem("no", "Norwegian" ),
            new DataSourceItem("ny", "Nyanja" ),
            new DataSourceItem("or", "Odia" ),
            new DataSourceItem("fa", "Persian" ),
            new DataSourceItem("pl", "Polish" ),
            new DataSourceItem("pt", "Portuguese" ),
            new DataSourceItem("pa", "Punjabi" ),
            new DataSourceItem("ro", "Romanian" ),
            new DataSourceItem("ru", "Russian" ),
            new DataSourceItem("sm", "Samoan" ),
            new DataSourceItem("gd", "Scottish Gaelic" ),
            new DataSourceItem("sr", "Serbian" ),
            new DataSourceItem("sn", "Shona" ),
            new DataSourceItem("si", "Sinhala" ),
            new DataSourceItem("sk", "Slovak" ),
            new DataSourceItem("sl", "Slovenian" ),
            new DataSourceItem("so", "Somali" ),
            new DataSourceItem("st", "Southern Sotho" ),
            new DataSourceItem("es", "Spanish" ),
            new DataSourceItem("su", "Sundanese" ),
            new DataSourceItem("sw", "Swahili" ),
            new DataSourceItem("sv", "Swedish" ),
            new DataSourceItem("tl", "Tagalog" ),
            new DataSourceItem("tg", "Tajik" ),
            new DataSourceItem("ta", "Tamil" ),
            new DataSourceItem("tt", "Tatar" ),
            new DataSourceItem("te", "Telugu" ),
            new DataSourceItem("th", "Thai" ),
            new DataSourceItem("bo", "Tibetan" ),
            new DataSourceItem("tr", "Turkish" ),
            new DataSourceItem("tk", "Turkmen" ),
            new DataSourceItem("uk", "Ukrainian" ),
            new DataSourceItem("ur", "Urdu" ),
            new DataSourceItem("ug", "Uyghur" ),
            new DataSourceItem("uz", "Uzbek" ),
            new DataSourceItem("vi", "Vietnamese" ),
            new DataSourceItem("cy", "Welsh" ),
            new DataSourceItem("fy", "Western Frisian" ),
            new DataSourceItem("wo", "Wolof" ),
            new DataSourceItem("xh", "Xhosa" ),
            new DataSourceItem("yi", "Yiddish" ),
            new DataSourceItem("yo", "Yoruba" ),
            new DataSourceItem("zu", "Zulu"),
        };
    }
}