using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.Taus.DataSourceHandlers;

public class LanguageDataHandler : IStaticDataSourceHandler
{
    protected Dictionary<string, string> EnumValues => new()
    {
        {"af", "Afrikaans" },
        {"sq", "Albanian" },
        {"am", "Amharic" },
        {"ar", "Arabic" },
        {"hy", "Armenian" },
        {"as", "Assamese" },
        {"az", "Azerbaijani" },
        {"bn", "Bangla" },
        {"eu", "Basque" },
        {"be", "Belarusian" },
        {"bs", "Bosnian" },
        {"bg", "Bulgarian" },
        {"my", "Burmese" },
        {"ca", "Catalan" },
        {"ceb", "Cebuano" },
        {"zh", "Chinese" },
        {"co", "Corsican" },
        {"hr", "Croatian" },
        {"cs", "Czech" },
        {"da", "Danish" },
        {"nl", "Dutch" },
        {"en", "English" },
        {"eo", "Esperanto" },
        {"et", "Estonian" },
        {"fi", "Finnish" },
        {"fr", "French" },
        {"gl", "Galician" },
        {"ka", "Georgian" },
        {"de", "German" },
        {"el", "Greek" },
        {"gu", "Gujarati" },
        {"ht", "Haitian Creole" },
        {"ha", "Hausa" },
        {"haw", "Hawaiian" },
        {"he", "Hebrew" },
        {"hi", "Hindi" },
        {"hmn", "Hmong" },
        {"hu", "Hungarian" },
        {"is", "Icelandic" },
        {"ig", "Igbo" },
        {"id", "Indonesian" },
        {"ga", "Irish" },
        {"it", "Italian" },
        {"ja", "Japanese" },
        {"jv", "Javanese" },
        {"kn", "Kannada" },
        {"kk", "Kazakh" },
        {"km", "Khmer" },
        {"rw", "Kinyarwanda" },
        {"ko", "Korean" },
        {"ku", "Kurdish" },
        {"ky", "Kyrgyz" },
        {"lo", "Lao" },
        {"la", "Latin" },
        {"lv", "Latvian" },
        {"lt", "Lithuanian" },
        {"lb", "Luxembourgish" },
        {"mk", "Macedonian" },
        {"mg", "Malagasy" },
        {"ms", "Malay" },
        {"ml", "Malayalam" },
        {"mt", "Maltese" },
        {"mr", "Marathi" },
        {"mn", "Mongolian" },
        {"mi", "Māori" },
        {"ne", "Nepali" },
        {"no", "Norwegian" },
        {"ny", "Nyanja" },
        {"or", "Odia" },
        {"fa", "Persian" },
        {"pl", "Polish" },
        {"pt", "Portuguese" },
        {"pa", "Punjabi" },
        {"ro", "Romanian" },
        {"ru", "Russian" },
        {"sm", "Samoan" },
        {"gd", "Scottish Gaelic" },
        {"sr", "Serbian" },
        {"sn", "Shona" },
        {"si", "Sinhala" },
        {"sk", "Slovak" },
        {"sl", "Slovenian" },
        {"so", "Somali" },
        {"st", "Southern Sotho" },
        {"es", "Spanish" },
        {"su", "Sundanese" },
        {"sw", "Swahili" },
        {"sv", "Swedish" },
        {"tl", "Tagalog" },
        {"tg", "Tajik" },
        {"ta", "Tamil" },
        {"tt", "Tatar" },
        {"te", "Telugu" },
        {"th", "Thai" },
        {"bo", "Tibetan" },
        {"tr", "Turkish" },
        {"tk", "Turkmen" },
        {"uk", "Ukrainian" },
        {"ur", "Urdu" },
        {"ug", "Uyghur" },
        {"uz", "Uzbek" },
        {"vi", "Vietnamese" },
        {"cy", "Welsh" },
        {"fy", "Western Frisian" },
        {"wo", "Wolof" },
        {"xh", "Xhosa" },
        {"yi", "Yiddish" },
        {"yo", "Yoruba" },
        {"zu", "Zulu" }
    };

    public Dictionary<string, string> GetData()
    {
        return EnumValues;
    }
}